### ISSUE TITLE
Nothing doesn't work. Maybe need update an instruction?

### ISSUE THREAD

**Issue by seralekseenko** [assistant-ai/jess#30]
I tried several commands. 

Request was:
```bash
seralekseenko@Kompik:~/Desktop/jess$ go run main.go dialog -c OpenAPI schema
Model that is used for this task: gpt3
Starting a new conversation...
You: what is the next step?
```
Response:
```bash
Thinking |ERRO[0015] error from llmClient in chat dialog          
panic: Error response from GPT: {
    "error": {
        "message": "",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_api_key"
    }
}


goroutine 1 [running]:
github.com/assistant-ai/jess/cli.HandleError(...)
	/home/seralekseenko/Desktop/jess/cli/terminal_utils.go:38
github.com/assistant-ai/jess/commands_context.handleDialogContinue({0x7ffea3e36d27, 0x7}, 0x7?, 0xc000112bc0?)
	/home/seralekseenko/Desktop/jess/commands_context/dialog_command.go:76 +0xcb
github.com/assistant-ai/jess/commands_context.handleDialogAction.func1(0xc0006bfb90?)
	/home/seralekseenko/Desktop/jess/commands_context/dialog_command.go:28 +0x7d
github.com/urfave/cli/v2.(*Command).Run(0xc0002ff760, 0xc0005a4140, {0xc0005a4180, 0x4, 0x4})
	/home/seralekseenko/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:274 +0x9eb
github.com/urfave/cli/v2.(*Command).Run(0xc000506840, 0xc0004e0500, {0xc0000360a0, 0x5, 0x5})
	/home/seralekseenko/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/command.go:267 +0xc4d
github.com/urfave/cli/v2.(*App).RunContext(0xc00022c5a0, {0xee1450?, 0xc0000400b8}, {0xc0000360a0, 0x5, 0x5})
	/home/seralekseenko/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
	/home/seralekseenko/go/pkg/mod/github.com/urfave/cli/v2@v2.25.1/app.go:309
main.main()
	/home/seralekseenko/Desktop/jess/main.go:29 +0x59
exit status 2
```

Request:
```bash
seralekseenko@Kompik:~/Desktop/jess$ go run main.go code explain -i /home/seralekseenko/Desktop/CBE_solutions/pom.xml
```
Response:
```bash
Model that is used for this task: gpt3
panic: sql: no rows in result set

goroutine 1 [running]:
github.com/assistant-ai/jess/cli.HandleError(...)
	/home/seralekseenko/Desktop/jess/cli/terminal_utils.go:38
main.main()
	/home/seralekseenko/Desktop/jess/main.go:30 +0x9e
exit status 2
```

Request:
```bash
seralekseenko@Kompik:~/Desktop/jess$ go run main.go process -p "Can you improve this file?" -i /home/seralekseenko/Desktop/CBE_solutions/pom.xml
```
Response:
```bash
Model that is used for this task: gpt3
panic: sql: no rows in result set

goroutine 1 [running]:
github.com/assistant-ai/jess/cli.HandleError(...)
	/home/seralekseenko/Desktop/jess/cli/terminal_utils.go:38
main.main()
	/home/seralekseenko/Desktop/jess/main.go:30 +0x9e
exit status 2
```

**Comment by b0noI** [comment]
fuck:( looks like MySQL again :(

**Comment by b0noI** [comment]
ahhhh: 
Thinking |ERRO[0015] error from llmClient in chat dialog          
panic: Error response from GPT: {
    "error": {
        "message": "",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_api_key"
    }
}

I might know where this is coming from, let's chat

**Comment by b0noI** [comment]
@seralekseenko can yo move you key file to ~/.jess/ folder?

**Comment by seralekseenko** [comment]
20 min and I'll do.

**Comment by seralekseenko** [comment]
@b0noI Hi )
What is next step?

**Comment by nikkrichko** [comment]
@seralekseenko, is it still reproducible after the latest changes?
Please verify (describe) the initial use case.

**Comment by seralekseenko** [comment]
@nikkrichko Now it is work as expected according the to the instructions.
